### ISSUE TITLE
Не работает с debugParser

### ISSUE THREAD

**Issue by TheGeneralov** [azernov/gitmodx#1]
Выдает 500 ошибку и в логах пишет
```
PHP Fatal error:  Uncaught Error: Call to undefined method debugPdoParser::getElementFromFileById() in /core/components/gitmodx/model/gitmodx/gitmodx.class.php:123
Stack trace:
#0 /core/model/modx/modx.class.php(1621): gitModx->getObject('modPlugin', Array, true)
#1 /core/model/modx/modrequest.class.php(70): modX->invokeEvent('OnHandleRequest')
#2 /core/model/modx/modx.class.php(1423): modRequest->handleRequest()
#3 /index.php(54): modX->handleRequest()
#4 {main}
thrown in /core/components/gitmodx/model/gitmodx/gitmodx.class.php on line 123

**Comment by azernov** [comment]
Похоже, что проблема в том, что у вас используется парсер debugPdoParser. GitModx рассчитан на работу со стандартным парсером modParser или pdoParser. Какой у вас установлен дополнительный компонент, который добавляет класс debugPdoParser?

**Comment by TheGeneralov** [comment]
https://modstore.pro/packages/utilities/debugparser
вот этот компонент
Просто есть сайт, который долго грузится. Хотел посмотреть что именно его так тормозит.

**Comment by azernov** [comment]
Я с debugparser никогда не работал, но тем не менее, можете попробовать заменить у себя файл core/components/gitmodx/model/gitmodx/gitmodparser.class.php на вот этот:

https://gist.github.com/azernov/7925f8ce65dc92a62d18a74091c2a536

Если что, в 5-й строке возможно нужно будет подкорректировать путь к файлу класса debugPdoParser. По идее должно работать, но не гарантирую, так как не тестировал.

**Comment by TheGeneralov** [comment]
Путь в 5 строке указал другой.
Но теперь весь сайт лег, даже админка.
В логах 
```PHP Fatal error:  Class 'pdoParser' not found in /core/components/debugparser/model/debugpdoparser.class.php on line 3```

**Comment by azernov** [comment]
Похоже, что debugPdoParser наследуется от pdoParser и их нужно совмещать более детально. Поэтому, к сожалению, пока вряд ли смогу помочь. Но возможно, что в ближайшем будущем установлю у себя тоже debugPdoParser  и налажу их совместную работу.

Проверьте у себя в системных настройках настройки parser_class и parser_class_path там должны стоять настройки gitmodx (gitModParser и {core_path}/components/gitmodx/model/gitmodx/ соответственно). Возможно там сейчас у вас стоят настройки debugPdoParser и поэтому все валится.

Если после замены настроек не заработает, то пока либо отключайте debugPdoParser, либо откажитесь от gitmodx. Я постараюсь в ближайшем будущем их подружить.

**Comment by TheGeneralov** [comment]
Настройки в порядке. Отказаться от gitModx не могу, по двум причинам.
1. Сайт весь написан с использованием gitModx, обратно экспортировать элементы нет инструмента.
2. Мне нравится работать с gitModx
Буду пробовать
