### ISSUE TITLE
Ошибку пишет gitmodx.class.php on line 63

### ISSUE THREAD

**Issue by aaa-artemius** [azernov/gitmodx#2]
```
Fatal error: Uncaught Error: Cannot use object of type xPDOQuery_mysql as array in \core\components\gitmodx\model\gitmodx\gitmodx.class.php:63 
Stack trace: #0 \core\model\modx\modprocessor.class.php(554): gitModx->getCount('modChunk', Object(xPDOQuery_mysql)) 
#1 \core\model\modx\modprocessor.class.php(488): modObjectGetListProcessor->getData() 
#2 \core\model\modx\modprocessor.class.php(173): modObjectGetListProcessor->process() 
#3 \core\model\modx\modx.class.php(1704): modProcessor->run() 
#4 \core\model\modx\modconnectorresponse.class.php(140): modX->runProcessor('mgr/system/elem...', Array, Array) 
#5 \core\model\modx\modconnectorrequest.class.php(82): modConnectorResponse->outputContent(Array) 
#6 \core\model\modx\modconnectorrequest.class.php(69): modConnectorRequest->prepareResponse(Array) 
#7 \assets\components\minishop2\conn in \core\components\gitmodx\model\gitmodx\gitmodx.class.php on line 63
```
Подскажите как можно исправить?

**Comment by azernov** [comment]
Попробуйте сейчас обновиться. Ошибка старая, просто я ее фикс совсем забыл выложить в репозиторий.

**Comment by aaa-artemius** [comment]
Спасибо!
